# Generated by Django 5.2 on 2025-12-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ENUM', 'Enumeration'), ('AUTH_ABUSE', 'Auth Abuse'), ('OTHER', 'Other')], max_length=32)),
                ('ip', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brokerbackend_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
