from django.core.management.base import BaseCommand
from django.conf import settings
from django.core.mail import send_mail, EmailMessage
from brokerBackend import alerting
import logging

logger = logging.getLogger(__name__)

class Command(BaseCommand):
    help = 'Send a test alert email, webhook and persist a test Alert record.'

    def add_arguments(self, parser):
        parser.add_argument('--subject', default='[Test] Alert from CRM', help='Email subject')
        parser.add_argument('--message', default='This is a test alert generated by send_test_alert.', help='Email body')
        parser.add_argument('--ip', default='127.0.0.1', help='IP to include in alert')
        parser.add_argument('--type', default='OTHER', help='Alert type (ENUM, AUTH_ABUSE, OTHER)')

    def handle(self, *args, **options):
        subject = options['subject']
        message = options['message']
        ip = options['ip']
        alert_type = options['type']

        recipients = getattr(settings, 'API_MONITOR_ALERT_RECIPIENTS', ['support@vtindex.com'])
        from_email = getattr(settings, 'DEFAULT_FROM_EMAIL', getattr(settings, 'SERVER_EMAIL', 'no-reply@vtindex.com'))

        # Send email using To + CC (first recipient is To, others are CC)
        try:
            to_list = [recipients[0]] if recipients else []
            cc_list = recipients[1:] if len(recipients) > 1 else []
            email = EmailMessage(subject, message, from_email, to=to_list, cc=cc_list)
            email.send(fail_silently=False)
            self.stdout.write(self.style.SUCCESS(f'Email sent To={to_list} CC={cc_list}'))
        except Exception as e:
            logger.exception('Failed to send test email')
            self.stdout.write(self.style.ERROR(f'Failed to send email: {e}'))

        # Persist alert
        try:
            a = alerting.record_alert(alert_type, ip=ip, path='/test/alert', details={'message': message})
            if a:
                self.stdout.write(self.style.SUCCESS(f'Alert persisted id={a.id}'))
            else:
                self.stdout.write(self.style.WARNING('Alert persistence returned None'))
        except Exception as e:
            logger.exception('Failed to persist test alert')
            self.stdout.write(self.style.ERROR(f'Failed to persist alert: {e}'))

        # Notify webhook
        try:
            ok = alerting.notify_webhook(alert_type, ip=ip, path='/test/alert', details={'message': message})
            if ok:
                self.stdout.write(self.style.SUCCESS('Webhook notification sent (or attempted).'))
            else:
                self.stdout.write(self.style.WARNING('No webhook configured or notify failed.'))
        except Exception as e:
            logger.exception('Failed to notify webhook in test command')
            self.stdout.write(self.style.ERROR(f'Failed to notify webhook: {e}'))
